/* generated by Makefile */
#define KSI_VERSION "3.9.1"
#define KSI_MAJOR_VERSION 3
#define KSI_MINOR_VERSION 9
#define KSI_PATCH_LEVEL 1
#define KSI_CPU "x86_64"
#define KSI_OS "mingw32"
#define KSI_SCM_LIB_DIR "/home/win64/share/ksi"
#define KSI_INSTAL_INCLUDE_DIR "/home/win64/include/ksi"
#define KSI_INSTAL_LIB_DIR "/home/win64/lib/ksi"
#define KSI_INSTAL_BIN_DIR "/home/win64/bin"
#define KSI_INSTAL_INFO_DIR "/home/win64/share/info"
#define KSI_INSTAL_MAN_DIR "/home/win64/share/man"
#define KSI_BUILD_CFLAGS "-Wall -DMAKE_si_LIB -DWIN32 -g -O2 -I/home/win64/include"
#define KSI_BUILD_LIBS "-liconv -lgmp -lgc -lm  "
#define KSI_DLLNAME "libksi-11.dll"
