/* generated by Makefile */
#define KSI_VERSION "3.5.1"
#define KSI_LIB_VERSION "3.5"
#define KSI_MAJOR_VERSION 3
#define KSI_MINOR_VERSION 5
#define KSI_PATCH_LEVEL 1
#define KSI_CPU "x86"
#define KSI_OS "linux"
#define KSI_SCM_LIB_DIR "/home/ksion/share/ksi"
#define KSI_INSTAL_INCLUDE_DIR "/home/ksion/include/ksi"
#define KSI_INSTAL_LIB_DIR "/home/ksion/lib/ksi"
#define KSI_INSTAL_BIN_DIR "/home/ksion/bin"
#define KSI_INSTAL_INFO_DIR "/home/ksion/share/info"
#define KSI_INSTAL_MAN_DIR "/home/ksion/share/man"
#define KSI_BUILD_CFLAGS "-Wall -g -O2 -D_REENTRANT -g3"
#define KSI_BUILD_LIBS "-lgc -ldl -lm  -lpthread "
