//=====================================================================
#include "stdafx.h"
#include "ksi.h"
//=====================================================================
ksi_obj
  keyCont,     keyColor,    keyFBColor,   keyFont,    keyHVis,
  keyLVis,     keySVis,     keyFill,      keyStrok,   keyFSolid,
  keyFHatched, keyPoly,     keyCoord,     keySize,    keyLines,
  keyPolyline, keyBpll,     keyOplg,      keySplg,    keyFplg,
  keyAngle,    keyHint,     keyIcon,      keyIconref, keyText,
  keyFootnote, keyContents, keyReference, keyString,  keyDelta,
  keyRule,     keyWndRule,  keyPoint,     keyArc,     keyRect,
  keyEllipse,  keyRefpoint, keyRoundrect, keyTxtItem, keyTextByLine,
  keyTable,    keyEntry,    keyObject,    keyClass,   keyStatus,
  keyNode,     keyShape;
//=====================================================================
