#ifndef __TPDEF_H__
#define __TPDEF_H__
//=====================================================================
#define CTabIdList    CList< CTabIdent, CTabIdent& >
#define CObjList      CList< CDrawObject*, CDrawObject* >
#define CTabIdArray   CArray< CTabIdent, CTabIdent& >
#define CIntArray     CArray< int, int >
#define CUndoList     CList< CUndoScaleItem*, CUndoScaleItem* >
//=====================================================================
#endif
